### ISSUE TITLE
.

### ISSUE THREAD

**Issue by webees** [lmxdawn/framework#1]

**Comment by lmxdawn** [comment]
我手里没有，我朋友有




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lmxdawn/framework"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月12日(星期三) 晚上6:19
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[lmxdawn/framework] 能分享下sql文件吗？ (Issue #1)

**Comment by webees** [comment]
朋友的朋友就是我的朋友，微信webees。红包安排！
